services:
  - type: web
    name: flame-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn minimal:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0